DEFAULT_PUBLISH_SOCKET = "/run/robot-pet/telemetry-pub.sock"
DEFAULT_SUBSCRIBE_SOCKET = "/run/robot-pet/telemetry-sub.sock"

DEFAULT_CAMERA_BIND_HOST = "0.0.0.0"
DEFAULT_CAMERA_PORT = 8081

DEFAULT_WEB_DASHBOARD_HOST = "0.0.0.0"
DEFAULT_WEB_DASHBOARD_PORT = 8080
